CREATE TABLE flashcard_dailies (
   id INTEGER PRIMARY KEY AUTO_INCREMENT,
   vocabulary_id INTEGER NOT NULL,
   topic VARCHAR(255) NOT NULL DEFAULT 'English',
   date DATE DEFAULT (CURDATE()),
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE user_daily_word_statistics ADD COLUMN date DATE DEFAULT (CURDATE());
ALTER TABLE user_flashcard_logs ADD COLUMN date DATE DEFAULT (CURDATE());
ALTER TABLE vocabularies ADD COLUMN topic VARCHAR(255) NULL DEFAULT 'English';
